name: Sync with GitLab

on:
  push:
    branches:
      - main
      - dev
      - qa
	  - uat
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Sync with GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.TOKEN }}@gitlab.com/jorgecardona/integration_github_gitlab.git
          git fetch gitlab
          if [ "${REF##*/}" == "dev" ]; then
            git push gitlab dev:dev
          elif [ "${REF##*/}" == "main" ]; then
            git push gitlab main:main
          elif [ "${REF##*/}" == "qa" ]; then
            git push gitlab qa:qa
          elif [ "${REF##*/}" == "uat" ]; then
            git push gitlab prod:uat
          elif [ "${REF##*/}" == "prod" ]; then
            git push gitlab prod:prod
          fi
