name: Sync with GitLab

on:
  push:
    branches:
      - main
      - dev
      - qa
      - uat
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync with GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/jorgecardona/integration_github_gitlab.git
          git fetch gitlab
          
          # Handle sync for each branch
          for branch in main dev qa uat prod; do
            git checkout $branch
            git rebase gitlab/$branch || {
              echo "Conflict or error occurred during rebase. Please resolve conflicts manually.";
              exit 1;
            }
            git push gitlab $branch:$branch || {
              echo "Error pushing branch $branch to GitLab.";
              exit 1;
            }
          done
